# Generated by Django 3.0.14 on 2022-10-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='login',
            field=models.CharField(default='gość', max_length=50),
            preserve_default=False,
        ),
    ]
