# Generated by Django 3.0.14 on 2022-08-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(db_index=True, max_length=200)),
                ('skrot_url', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(db_index=True, max_length=200)),
                ('skrot_url', models.SlugField(max_length=200)),
                ('zdjecie', models.ImageField(blank=True, upload_to='Produkty/%Y/%m/%d')),
                ('opis', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostepny', models.BooleanField(default=True)),
                ('utworzony', models.DateTimeField(auto_now_add=True)),
                ('zaktualizowany', models.DateTimeField(auto_now=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty', to='sklep.Kategoria')),
            ],
            options={
                'verbose_name': 'artykuł',
                'verbose_name_plural': 'artykuły',
                'ordering': ('nazwa',),
                'index_together': {('id', 'skrot_url')},
            },
        ),
    ]
