# Generated by Django 3.0.14 on 2022-10-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_rating_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
