# Generated by Django 3.0.14 on 2022-10-01 03:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uzytkownicy', '0001_initial'),
        ('sklep', '0003_auto_20221001_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwiazdki', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.Produkt')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.Uzytkownik')),
            ],
        ),
    ]
