# Generated by Django 4.1.2 on 2022-10-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceny', '0003_alter_ocena_uzytkownik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='product',
            new_name='produkt',
        ),
    ]
