# Generated by Django 3.0.14 on 2022-10-01 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0001_initial'),
        ('zamowienia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='email',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='kod_pocztowy',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='miasto',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='uzytkownik',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='użytkownik', to='uzytkownicy.Uzytkownik'),
            preserve_default=False,
        ),
    ]
