# Generated by Django 3.0.14 on 2022-10-01 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0003_auto_20221001_0655'),
        ('zamowienia', '0002_auto_20221001_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzytkownik', to='uzytkownicy.Uzytkownik'),
        ),
    ]
