# Generated by Django 3.0.14 on 2022-10-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0004_auto_20221001_0906'),
        ('zamowienia', '0003_auto_20221001_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzytkownik', to='uzytkownicy.UzytkownikProfil'),
        ),
    ]
