# Generated by Django 3.0.14 on 2022-10-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0004_auto_20221001_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='adres',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='kod_pocztowy',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='miasto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
