# Generated by Django 3.0.14 on 2022-08-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.CharField(max_length=250)),
                ('kod_pocztowy', models.CharField(max_length=20)),
                ('miasto', models.CharField(max_length=100)),
                ('utworzone', models.DateTimeField(auto_now_add=True)),
                ('zaktualizowane', models.DateTimeField(auto_now=True)),
                ('zaplacone', models.BooleanField(default=False)),
                ('id_serwisu_platniczego', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
                'ordering': ('-utworzone',),
            },
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje_zamowienia', to='sklep.Produkt')),
                ('zamówienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artykuly', to='orders.Zamowienie')),
            ],
        ),
    ]
